name: Build Pages
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.32.6
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "pnpm"

      - name: Cache .pnpm-store
        uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm-store
            D:\.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}
            
      - name: Install Dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm i

      # Vite Build.
      - name: Generates Pages
        run: |
          pnpm build
      - name: Deploy Github Pages🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          repository-name: toimc-team/vue3-toimc-admin
          branch: gh-pages
          folder: ./dist # The folder the action should deploy.
          ssh-key: ${{ secrets.GITEE_PRIVATE_KEY }}
            
      - name: Sync to Gitee 
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:toimc-team/vue3-toimc-admin.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:toimc-team/vue3-toimc-admin.git

      - name: Sync Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: toimc
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: toimc-team/vue3-toimc-admin
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh-pages
